kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: runner-cache
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem