apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  namespace: {{ .Release.Namespace }}
  name: docker
spec:
  source:
    type: Dockerfile
    dockerfile: |
      FROM docker:dind

      # Install software
      RUN apk --update --no-cache add fuse-overlayfs rsync
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 0
  failedBuildsHistoryLimit: 1
  runPolicy: Serial
  triggers:
    - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: 'docker:dind'

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: docker
  namespace: {{ .Release.Namespace }}