kind: ConfigMap
apiVersion: v1
metadata:
  name: post
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: post
data:
  application.yaml: |
    spring:
      application:
        name: post
      config:
        import:
          - classpath:postgresql.yaml
          - classpath:vault.yaml
          - classpath:s3.yaml
      main:
        web-application-type: reactive
      security:
        authentication:
          header: Authentication
          jwt:
            secret: ${jwt.secret}
    github:
      uri: https://api.github.com
    management:
      endpoint:
        health:
          probes:
            enabled: true
    server:
      port: 8080
      external-url: https://{{ .Values.host }}
