kind: Service
apiVersion: v1
metadata:
  name: post
  namespace: {{ .Release.Namespace }}
  labels:
    type: client
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: post
