spring:
  datasource:
    url: ${database_url}
    username: ${database_username}
    password: ${database_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 0