apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-github-actions-runner
  namespace: openshift-gitops
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: 'https://kubernetes.default.svc'
  project: {{ .Release.Namespace }}
  sources:
    - path: charts/github-actions-runner
      repoURL: 'https://github.com/sayaya1090/sayaya.git'
      targetRevision: HEAD
      helm:
        values: |
          arc:
            nameOverride: "arc"
            fullnameOverride: "arc"
          ubi9:
            runnerScaleSetName: "ubi9"
            githubConfigUrl: https://github.com/sayaya1090/sayaya
            githubConfigSecret: github-secret
            minRunners: 3
            maxRunners: 8
            template:
              spec:
                serviceAccountName: builder
                initContainers:
                  - name: init-dind-externals
                    image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/actions-runner:latest
                    command: [ "cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/" ]
                    volumeMounts:
                      - name: dind-externals
                        mountPath: /home/runner/tmpDir
                  - name: init-cache
                    image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/actions-runner:latest
                    securityContext:
                      runAsUser: 1000
                      privileged: true
                    command:
                      - /bin/sh
                      - -c
                      - |
                        rsync -a /home/runner/cache/_work /home/runner/ || true
                        rsync -a /home/runner/cache/gradle-installations/installs /home/runner/gradle-installations/ || true
                        rsync -a /home/runner/cache/.gradle /home/runner/ || true
                        rsync -a /home/runner/cache/docker/fuse-overlayfs /var/lib/docker/ || true
                    volumeMounts:
                      - name: cache
                        mountPath: /home/runner/cache
                      - name: work
                        mountPath: /home/runner/_work
                      - name: gradle-installation
                        mountPath: /home/runner/gradle-installations/installs
                      - name: gradle
                        mountPath: /home/runner/.gradle
                      - name: docker
                        mountPath: /var/lib/docker/fuse-overlayfs
                containers:
                  - name: runner
                    image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/actions-runner:latest
                    command: [ "/home/runner/run.sh" ]
                    securityContext:
                      runAsUser: 1000
                      privileged: true
                    env:
                      - name: DOCKER_HOST
                        value: unix:///var/run/docker.sock
                    volumeMounts:
                      - name: work
                        mountPath: /home/runner/_work
                      - name: gradle-installation
                        mountPath: /home/runner/gradle-installations/installs
                      - name: gradle
                        mountPath: /home/runner/.gradle
                      - name: dind-sock
                        mountPath: /var/run
                      - name: cache
                        mountPath: /home/runner/cache
                    lifecycle:
                      preStop:
                        exec:
                          command:
                            - rsync -a --exclude=_temp/* ~/_work ~/cache/ || true &&
                            - rsync -a ~/gradle-installations/installs ~/cache/gradle-installations/ || true &&
                            - rsync -a ~/.gradle ~/cache/ || true
                  - name: dind
                    image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/docker:dind
                    args: [ "dockerd", "--host=unix:///var/run/docker.sock", "--group=$(DOCKER_GROUP_GID)" ]
                    env:
                      - name: DOCKER_GROUP_GID
                        value: "123"
                    securityContext:
                      privileged: true
                    volumeMounts:
                      - name: work
                        mountPath: /home/runner/_work
                      - name: docker
                        mountPath: /var/lib/docker/fuse-overlayfs
                      - name: dind-sock
                        mountPath: /var/run
                      - name: dind-externals
                        mountPath: /home/runner/externals
                      - name: daemon-json
                        mountPath: /etc/docker/daemon.json
                        subPath: daemon.json
                        readOnly: true
                      - name: cache
                        mountPath: /home/runner/cache
                    lifecycle:
                      preStop:
                        exec:
                          command:
                            - rsync -a /var/lib/docker/fuse-overlayfs /home/runner/cache/docker || true
                volumes:
                  - name: work
                    emptyDir: { }
                  - name: dind-sock
                    emptyDir: { }
                  - name: dind-externals
                    emptyDir: { }
                  - name: daemon-json
                    configMap:
                      name: docker-daemon-config
                  - name: gradle-installation
                    emptyDir: { }
                  - name: gradle
                    emptyDir: { }
                  - name: docker
                    emptyDir: { }
                  - name: cache
                    persistentVolumeClaim:
                      claimName: runner-cache
            controllerServiceAccount:
              namespace: {{ .Release.Namespace }}
              name: arc
  revisionHistoryLimit: 0
  syncPolicy:
    syncOptions:
      - ServerSideApply=true