apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-watcher
  namespace: {{ .Release.Namespace }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-watcher-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-watcher
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: service-watcher
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: service-watcher-role