apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-backup
  namespace: {{ .Release.Namespace }}
spec:
  backupOwnerReference: self
  cluster:
    name: postgresql
  schedule: 0 1 0 * * 0