apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: bucket
  namespace: {{ .Release.Namespace }}
spec:
  bucketName: {{ .Values.bucket }}
  storageClassName: ocs-storagecluster-ceph-rgw
  additionalConfig:
    maxSize: {{ .Values.bucketMaxSize }}
