apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.host }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ .Values.host }}
  dnsNames:
    - {{ .Values.host }}
    - vault.{{ .Values.host }}
    - s3.{{ .Values.host }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ .Values.host }}-ca