apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-https
  namespace: {{ .Values.targetNamespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - {{ .Values.host }}
        - vault.{{ .Values.host }}
        - s3.{{ .Values.host }}
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.host }}-ca