apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: postgres-dynamic-secret
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    create: false
    name: postgresql-app
  mount: database
  path: creds/sayaya
  renewalPercent: 67
  rolloutRestartTargets: []